enable-magisk-update = true
compression-level = 9
parallel-jobs = 1
rv-brand = "ReVanced Extended"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "reddxae/revanced-patches"
patches-version = "latest"
integrations-source = "inotia00/revanced-integrations"
arch = "arm64-v8a"
build-mode = "module"
version = "19.50.41"
included-patches = "'MaterialYou' 'Return YouTube Username'"
excluded-patches = "'Hide accessibility controls dialog' 'Enable debug logging'"
patcher-args = "-e 'Custom branding name for YouTube' -OappName=YouTube -e 'Theme' -OdarkThemeBackgroundColor=@android:color/black -OlightThemeBackgroundColor=@android:color/white -e 'Visual preferences icons for YouTube' -OsettingsMenuIcon=revanced -OapplyToAll=true -e 'Custom branding icon for YouTube' -OappIcon=youtube -OrestoreOldSplashAnimation=true -e 'Overlay buttons' -OiconType=thin -OwiderButtonsSpace=true -OchangeTopButtons=true -e 'Settings for YouTube' -OrvxSettingsLabel='ReVanced Extended' -OinsertPosition=@string/about_key -e 'SponsorBlock' -OoutlineIcon=true"
module-prop-name = "youtube-revanced-extended" 
